__pipeline__:
  name: grandcanyon
  main: main.j2
  description: Human CHM13 genomics suite
  version: 0.0.1.dev
constants:
  tools:
    assembly-stats:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/assembly-stats_1.0.1--h4ac6f70_7.sif
    bcftools:
      container: /home/tgenref/containers/grandcanyon/common_tools/bcftools_1.17--h3cc50cf_1.sif
    busco:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/busco_5.5.0--pyhdfd78af_0.sif
    canu:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/canu_2.2--ha47f30e_0.sif
    cutesv:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/cutesv_2.0.3--pyhdfd78af_0.sif
    deepvariant:
      container: /home/tgenref/containers/grandcanyon/variant_calling/deepvariant_1.5.0-gpu.sif
    dorado:
      container: /home/tgenref/containers/grandcanyon/oxford_nanopore/dorado_0.3.4.sif
    dysgu:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/dysgu_1.5.0--py310h770aed0_1.sif
    featureCounts:
      container: /home/ehutchins/tools/subread_2.0.6--he4a0461_0.sif
    fgbio:
      container: pbc-art-prd01.ad.tgen.org/hpc-virtual-containers/external/fgbio:2.0.2-v1
    flair:
      container: /home/tgenref/containers/grandcanyon/rna_tools/flair_2.0.0--pyhdfd78af_1.sif
    flye:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/flye_2.9.2--py310h2b6aa90_2.sif
    gatk:
      container: /home/tgenref/containers/grandcanyon/common_tools/gatk_4.4.0.0.sif
    hifiasm:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/hifiasm_0.19.5--h43eeafb_2.sif
    hificnv:
      container: /home/tgenref/containers/grandcanyon/copy_number/hificnv_0.1.6b--h9ee0642_0.sif
    isoquant:
      container: /home/ehutchins/tools/isoquant_3.3.1--hdfd78af_0.sif
    isoseq3:
      container: /home/tgenref/containers/grandcanyon/rna_tools/isoseq3_4.0.0--h9ee0642_0.sif
    medaka:
      container: /home/tgenref/containers/grandcanyon/oxford_nanopore/medaka_1.8.0--py38hdaa7744_0.sif
    minimap2:
      container: pbc-art-prd01.ad.tgen.org/hpc-virtual-containers/minimap2-samtools:2.24-v1
    pbbam:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbbam_2.1.0--h8db2425_5.sif
    pbipa:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbipa_1.8.0--h6ead514_2.sif
    pbmm2:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbmm2_1.12.0--h9ee0642_0.sif
    pbsv:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbsv_2.9.0--h9ee0642_0.sif
    pbtk:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbtk_3.1.0--h9ee0642_0.sif
    pychopper:
      container: /home/ehutchins/tools/pychopper_2.5.0--py_0.sif
    salmon:
      container: /home/ehutchins/tools/salmon_1.10.2--hecfa306_0.sif
    samtools:
      container: /home/tgenref/containers/grandcanyon/common_tools/samtools_1.17--hd87286a_1.sif
    shasta:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/shasta_0.11.1--h4ac6f70_2.sif
    sniffles:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/sniffles_2.2--pyhdfd78af_0.sif
    verkko:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/verkko_1.4.1--h48217b1_0.sif
  grandcanyon:
    species: Homo sapiens
    genome_build: t2t_chm13
    genome_subversion_name: chm13v2
    gene_model_name: ensembl_v110
    gene_model_version: 110
    reference_fasta: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fa
    reference_fastaSIRV: /home/ehutchins/SIRV-4/SIRV_Set4_Norm_Sequences_20210507/SIRV_ERCC_longSIRV_multi-fasta_20210507.fasta
    reference_fai: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fai
    reference_dict: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.dict
    gtf: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_06-genes.gtf
    gtfSIRV: /home/ehutchins/SIRV-4/SIRV_Set4_Norm_Sequences_20210507/SIRV_ERCC_longSIRV_multi-fasta_20210507.gtf
    transcriptome: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_07-cdna.fa
    transcriptomeSIRV: /home/ehutchins/SIRV-4/SIRV_Set4_Norm_Sequences_20210507/SIRV_ERCC_longSIRV_multi-fasta_20210507_transcriptome.fa
