__pipeline__:
  name: grandcanyon
  main: main.j2
  description: Human CHM13 genomics suite
  version: 0.0.1.dev1
constants:
  tools:
    assembly-stats:
      container: quay.io/biocontainers/assembly-stats:1.0.1--h4ac6f70_7
    bcftools:
      container: quay.io/biocontainers/bcftools:1.18--h8b25389_0
    busco:
      container: quay.io/biocontainers/busco:5.5.0--pyhdfd78af_0
    canu:
      container: quay.io/biocontainers/canu:2.2--ha47f30e_0
    cutesv:
      container: quay.io/biocontainers/cutesv:2.0.3--pyhdfd78af_0
    cytocad:
      container: quay.io/biocontainers/cytocad:1.0.3--py310h4b81fae_2
    deepvariant:
      container: google/deepvariant:1.6.0-gpu
    dysgu:
      container: quay.io/biocontainers/dysgu:1.6.2--py310h770aed0_0
    flair:
      container: quay.io/biocontainers/flair:2.0.0--pyhdfd78af_1
    flye:
      container: quay.io/biocontainers/flye:2.9.2--py310h2b6aa90_2
    gatk:
      container: broadinstitute/gatk:4.4.0.0
    hifiasm:
      container: quay.io/biocontainers/hifiasm:0.19.8--h43eeafb_0
    hificnv:
      container: quay.io/biocontainers/hificnv:0.1.7--h9ee0642_0
    isoquant:
      container: quay.io/biocontainers/isoquant:3.3.1--hdfd78af_0
    longshot:
      container: quay.io/biocontainers/longshot:0.4.5--hd175d40_2
    lorax:
      container: quay.io/biocontainers/lorax:0.3.8--hb7e2ac5_0
    margin:
      container: /home/tgenref/containers/margin_latest.sif
    medaka:
      container: quay.io/biocontainers/medaka:1.11.1--py310h87e71ce_0
    minimap2:
      container: /home/tgenref/containers/minimap2-samtools_2.26_1.18.sif
    pbsv:
      container: quay.io/biocontainers/pbsv:2.9.0--h9ee0642_0
    pychopper:
      container: quay.io/biocontainers/pychopper:2.5.0--py_0
    salmon:
      container: quay.io/biocontainers/salmon:1.10.2--hecfa306_0
    samtools:
      container: quay.io/biocontainers/samtools:1.18--h50ea8bc_1
    severus:
      container: quay.io/biocontainers/severus:0.1.1--pyhdfd78af_0
    shasta:
      container: quay.io/biocontainers/shasta:0.11.1--h4ac6f70_2
    sniffles:
      container: quay.io/biocontainers/sniffles:2.2--pyhdfd78af_0
    subread:
      container: quay.io/biocontainers/subread:2.0.6--he4a0461_0
    vep:
      container: ensemblorg/ensembl-vep:release_107.0
    verkko:
      container: quay.io/biocontainers/verkko:1.4.1--h48217b1_0
    whatshap:
      container: quay.io/biocontainers/whatshap:2.2--py310h0dbaff4_0
  grandcanyon:
    species: Homo sapiens
    genome_build: t2t_chm13
    genome_subversion_name: chm13v2
    gene_model_name: ensembl_v107
    gene_model_version: 107
    reference_fasta: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fa
    reference_fai: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fai
    reference_fastaSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/genome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507.fa
    reference_faiSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/genome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507.fa.fai
    reference_dict: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.dict
    gtf: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_06-genes.ucsc.gtf
    gtfSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/gene_model/SIRV_ERCC_longSIRV_multi-fasta_20210507.gtf
    transcriptome: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_07-cdna.fa
    transcriptomeSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/transcriptome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507_transcriptome.fa
    vep_data: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/indexed_vep_data
