__pipeline__:
  name: grandcanyon
  main: main.jst
  description: Human CHM13 genomics suite
  version: 0.0.1.dev
constants:
  tools:
    minimap2:
      container: /home/tgenref/containers/grandcanyon/alignment/minimap2_2.26--he4a0461_1.sif
      digest: notarealdigest
    canu:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/canu_2.2--ha47f30e_0.sif
      digest: notarealdigest
    hifiasm:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/hifiasm_0.19.5--h43eeafb_2.sif
      digest: notarealdigest
    verkko:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/verkko_1.4.1--h48217b1_0.sif
      digest: notarealdigest
    assembly-stats:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/assembly-stats_1.0.1--h4ac6f70_7.sif
      digest: notarealdigest
    shasta:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/shasta_0.11.1--h4ac6f70_2.sif
      digest: notarealdigest
    flye:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/flye_2.9.2--py310h2b6aa90_2.sif
      digest: notarealdigest
    busco:
      container: /home/tgenref/containers/grandcanyon/assembly_tools/busco_5.5.0--pyhdfd78af_0.sif
      digest: notarealdigest
    samtools:
      container: /home/tgenref/containers/grandcanyon/common_tools/samtools_1.17--hd87286a_1.sif
      digest: notarealdigest
    bcftools:
      container: /home/tgenref/containers/grandcanyon/common_tools/bcftools_1.17--h3cc50cf_1.sif
      digest: notarealdigest
    gatk:
      container: /home/tgenref/containers/grandcanyon/common_tools/gatk_4.4.0.0.sif
      digest: notarealdigest
    hificnv:
      container: /home/tgenref/containers/grandcanyon/copy_number/hificnv_0.1.6b--h9ee0642_0.sif
      digest: notarealdigest
    dorado:
      container: /home/tgenref/containers/grandcanyon/oxford_nanopore/dorado_0.3.4.sif
      digest: notarealdigest
    medaka:
      container: /home/tgenref/containers/grandcanyon/oxford_nanopore/medaka_1.8.0--py38hdaa7744_0.sif
      digest: notarealdigest
    pbccs:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbccs_6.4.0--h9ee0642_0.sif
      digest: notarealdigest
    pbsim2:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbsim2_2.0.1--h4ac6f70_3.sif
      digest: notarealdigest
    pbmarkdup:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbmarkdup_1.0.3--h9ee0642_0.sif
      digest: notarealdigest
    pbskera:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbskera_1.1.0--hdfd78af_0.sif
      digest: notarealdigest
    pbbam:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbbam_2.1.0--h8db2425_5.sif
      digest: notarealdigest
    pbmm2:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbmm2_1.12.0--h9ee0642_0.sif
      digest: notarealdigest
    pbh5tools:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbh5tools_0.8.0--py27h9801fc8_6.sif
      digest: notarealdigest
    pbiotools:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbiotools_4.0.1--pyh7cba7a3_1.sif
      digest: notarealdigest
    pbpigeon:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbpigeon_1.1.0--h4ac6f70_0.sif
      digest: notarealdigest
    pbsv:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbsv_2.9.0--h9ee0642_0.sif
      digest: notarealdigest
    pbhoover:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbhoover_1.1.0--pyhdfd78af_1.sif
      digest: notarealdigest
    pbwt:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbwt_3.0--h6141fd1_9.sif
      digest: notarealdigest
    pbfusion:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbfusion_0.3.0--hdfd78af_0.sif
      digest: notarealdigest
    pbjasmine:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbjasmine_2.0.0--h9ee0642_0.sif
      digest: notarealdigest
    pbtk:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbtk_3.1.0--h9ee0642_0.sif
      digest: notarealdigest
    pbipa:
      container: /home/tgenref/containers/grandcanyon/pacbio/pbipa_1.8.0--h6ead514_2.sif
      digest: notarealdigest
    isoseq3:
      container: /home/tgenref/containers/grandcanyon/rna_tools/isoseq3_4.0.0--h9ee0642_0.sif
      digest: notarealdigest
    flair:
      container: /home/tgenref/containers/grandcanyon/rna_tools/flair_2.0.0--pyhdfd78af_1.sif
      digest: notarealdigest
    cutesv:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/cutesv_2.0.3--pyhdfd78af_0.sif
      digest: notarealdigest
    sniffles:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/sniffles_2.2--pyhdfd78af_0.sif
      digest: notarealdigest
    dysgu:
      container: /home/tgenref/containers/grandcanyon/structural_variant_calling/dysgu_1.5.0--py310h770aed0_1.sif
      digest: notarealdigest
    deepvariant:
      container: /home/tgenref/containers/grandcanyon/variant_calling/deepvariant_1.5.0-gpu.sif
      digest: notarealdigest
  grandcanyon:
    species: Homo sapiens
    genome_build: t2t_chm13
    genome_subversion_name: chm13v2
    gene_model_name: ensembl_v110
    gene_model_version: 110
    reference_fasta: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fa
    reference_fai: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fai    
    reference_dict: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.dict
    gtf: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_06-genes.gtf
    vep_data: /home/tgenref/homo_sapiens/grch38_hg38/tool_specific_resources/vep/v103/
