__pipeline__:
  name: grandcanyon
  main: main.j2
  description: Human CHM13 genomics suite
  version: 0.0.1.dev1
  bin: required_scripts/
constants:
  tools:
    assembly_stats:
      container: quay.io/biocontainers/assembly-stats:1.0.1--h4ac6f70_7
    bcftools:
      container: quay.io/biocontainers/bcftools:1.18--h8b25389_0
    busco:
      container: quay.io/biocontainers/busco:5.5.0--pyhdfd78af_0
    canu:
      container: quay.io/biocontainers/canu:2.2--ha47f30e_0
    clair3:
      container: hkubal/clair3:v1.0.5
    clairs:
      container: hkubal/clairs:v0.1.7
    cutesv:
      container: quay.io/biocontainers/cutesv:2.0.3--pyhdfd78af_0
    cytocad:
      container: quay.io/biocontainers/cytocad:1.0.3--py310h4b81fae_2
    deepsomatic:
      container: google/deepsomatic:1.6.0-gpu
    deepvariant:
      container: google/deepvariant:1.6.0-gpu
    dysgu:
      container: quay.io/biocontainers/dysgu:1.6.2--py310h770aed0_0
    flair:
      container: quay.io/biocontainers/flair:2.0.0--pyhdfd78af_1
    flye:
      container: quay.io/biocontainers/flye:2.9.2--py310h2b6aa90_2
    gatk:
      container: broadinstitute/gatk:4.4.0.0
    hifiasm:
      container: quay.io/biocontainers/hifiasm:0.19.8--h43eeafb_0
    hificnv:
      container: quay.io/biocontainers/hificnv:0.1.7--h9ee0642_0
    isoquant:
      container: quay.io/biocontainers/isoquant:3.3.1--hdfd78af_0
    longshot:
      container: quay.io/biocontainers/longshot:0.4.5--hd175d40_2
    lorax:
      container: quay.io/biocontainers/lorax:0.3.8--hb7e2ac5_0
    margin:
      container: /home/tgenref/containers/margin_latest.sif
    mashmap:
      container: /home/tgenref/containers/mashmap_3.1.3--h07ea13f_0.sif
    medaka:
      container: quay.io/biocontainers/medaka:1.11.1--py310h87e71ce_0
    minimap2:
      container: /home/tgenref/containers/minimap2-samtools_2.26_1.18.sif
    moddotplot:
      container: /home/tgenref/containers/moddotplot_latest.sif
    pafplot:
      container: /home/tgenref/containers/pafplot.sif
    pafr:
      container: /home/tgenref/containers/pafr.sif
    pbsv:
      container: quay.io/biocontainers/pbsv:2.9.0--h9ee0642_0
    pychopper:
      container: quay.io/biocontainers/pychopper:2.5.0--py_0
    python3:
      container: python:3.7.16-slim-bullseye
    python3_with_modules:
      container: ghcr.io/tgen/jetstream_containers/python:3.7.2-v1-with_modules
    quast:
      container: quay.io/biocontainers/quast:5.2.0--py39pl5321h4e691d4_3
    R:
      container: ghcr.io/tgen/containers/r_with_modules:4.1.2-23080815
    salmon:
      container: quay.io/biocontainers/salmon:1.10.2--hecfa306_0
    samtools:
      container: quay.io/biocontainers/samtools:1.18--h50ea8bc_1
    severus:
      container: quay.io/biocontainers/severus:0.1.2--pyhdfd78af_0
    shasta:
      container: quay.io/biocontainers/shasta:0.11.1--h4ac6f70_2
    sniffles:
      container: quay.io/biocontainers/sniffles:2.2--pyhdfd78af_0
    subread:
      container: quay.io/biocontainers/subread:2.0.6--he4a0461_0
    vep:
      container: ensemblorg/ensembl-vep:release_107.0
    verkko:
      container: quay.io/biocontainers/verkko:2.0--h45dadce_0
    whatshap:
      container: quay.io/biocontainers/whatshap:2.2--py310h0dbaff4_0
  grandcanyon:
    species: Homo sapiens
    genome_build: t2t_chm13
    genome_subversion_name: chm13v2
    gene_model_name: ensembl_v107
    gene_model_version: 107
    reference_fasta: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fa
    reference_fai: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.fai
    reference_fastaSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/genome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507.fa
    reference_faiSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/genome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507.fa.fai
    reference_dict: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/genome_reference/chm13v2.0_maskedY_rCRS.dict
    gtf: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_06-genes.ucsc.gtf
    gtfSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/gene_model/SIRV_ERCC_longSIRV_multi-fasta_20210507.gtf
    transcriptome: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/Homo_sapiens-GCA_009914755.4-2022_07-cdna.fa
    transcriptomeSIRV: /home/tgenref/homo_sapiens/t2t_chm13/SIRV/transcriptome_reference/SIRV_ERCC_longSIRV_multi-fasta_20210507_transcriptome.fa
    vep_data: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/gene_model/indexed_vep_data
    ref_flat: /home/tgenref/homo_sapiens/grch38_hg38/hg38_tempe/gene_model/ensembl_v103/Homo_sapiens.GRCh38.103.ucsc.refFlat.txt
    ribo_locations: /home/tgenref/homo_sapiens/grch38_hg38/hg38_tempe/gene_model/ensembl_v103/Homo_sapiens.GRCh38.103.ucsc.ribo.interval_list
    dbsnp: /home/tgenref/homo_sapiens/t2t_chm13/public_databases/dbsnp/chm13v2.0_dbSNPv155.vcf.gz
    gnomad: /home/tgenref/homo_sapiens/t2t_chm13/public_databases/gnomad/Homo_sapiens-GCA_009914755.4-2022_10-gnomad.vcf.gz
    clinvar: /home/tgenref/homo_sapiens/t2t_chm13/public_databases/clinvar/chm13v2.0_ClinVar20220313.vcf.gz
    tool_resources:
      severus:
        vntrs: /home/tgenref/homo_sapiens/t2t_chm13/chm13_v2/tool_resources/severus/chm13.bed
    required_scripts:
      plotSamStats_Rscript: summarize_samstats.R
      pafr_plot_Rscript: assembly_pafr_plot.R
      stats2json: samStats2json.py
      stats2lims: uploadStats2Lims.py
    lims_contigs: "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,
      chrY,
      chrM,
      chrUn_GL000220v1,
      chr22_KI270733v1_random,
      chrUn_KN707925v1_decoy,
      chr14_KI270726v1_random,
      chrUn_JTFH01000119v1_decoy,
      chrUn_JTFH01000204v1_decoy,
      chrUn_JTFH01000678v1_decoy,
      chrUn_JTFH01000497v1_decoy,
      chrUn_KN707927v1_decoy,
      chrUn_JTFH01000562v1_decoy,
      chrUn_JTFH01000659v1_decoy,
      chrUn_JTFH01001134v1_decoy,
      chrUn_JTFH01000888v1_decoy,
      chrUn_JTFH01000695v1_decoy,
      chrUn_JTFH01000697v1_decoy"
    strandedness_options:
      inward-unstranded-notapplicable:
        salmon: "IU"
        featurecounts: "0"
        collectrnaseqmetrics: "NONE"
      inward-stranded-forward:
        salmon: "ISF"
        featurecounts: "1"
        collectrnaseqmetrics: "FIRST_READ_TRANSCRIPTION_STRAND"
      inward-stranded-reverse:
        salmon: "ISR"
        featurecounts: "2"
        collectrnaseqmetrics: "SECOND_READ_TRANSCRIPTION_STRAND"
      singleend-unstranded-notapplicable:
        salmon: "IU"
        featurecounts: "0"
        collectrnaseqmetrics: "NONE"
      singleend-stranded-forward:
        salmon: "ISF"
        featurecounts: "1"
        collectrnaseqmetrics: "FIRST_READ_TRANSCRIPTION_STRAND"
      singleend-stranded-reverse:
        salmon: "ISR"
        featurecounts: "2"
        collectrnaseqmetrics: "SECOND_READ_TRANSCRIPTION_STRAND"
